-- Default password is test123
ALTER TABLE personne
ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '$2a$10$zNv/YHKwvx56B7pCDEfnfO3x/0kPf3vWX3I/NcpgqlZFpzxkqJc1S';
ALTER TABLE personne
ALTER COLUMN password TYPE VARCHAR(255);
ALTER TABLE personne ADD COLUMN is_admin BOOLEAN NOT NULL DEFAULT FALSE;
